/*
	FlexNav.js 0.7

	Copyright 2013, Jason Weaver http://jasonweaver.name
	Released under the WTFPL license
	http://sam.zoy.org/wtfpl/

//
*/

(function(){$.fn.flexNav=function(e){var t,n,r,i,s,o;return o=$.extend({animationSpeed:100},e),t=$(this),i=!1,r=!1,t.find("li").each(function(){if($(this).has("ul").length)return $(this).addClass("item-with-ul").find("ul").hide()}),t.data("breakpoint")&&(n=t.data("breakpoint")),s=function(){return $(window).width()<=n?(t.removeClass("lg-screen").addClass("sm-screen"),$(".one-page li a").on("click",function(){return t.removeClass("show")}),$(".item-with-ul").off()):(t.removeClass("sm-screen").addClass("lg-screen"),t.removeClass("show"),$(".item-with-ul").on("mouseenter",function(){return $(this).find(">ul").addClass("show").stop(!0,!0).slideDown(o.animationSpeed)}).on("mouseleave",function(){return $(this).find(">ul").removeClass("show").stop(!0,!0).slideUp(o.animationSpeed)}))},$(".item-with-ul, .menu-button").append('<span class="touch-button"><i class="navicon">&#9660;</i></span>'),$(".menu-button, .menu-button .touch-button").on("touchstart mousedown",function(e){return e.preventDefault(),e.stopPropagation(),console.log(r),$(this).on("touchmove mousemove",function(e){var t;return t=e.pageX,r=!0,$(window).off("touchmove mousemove")})}).on("touchend mouseup",function(e){var n;e.preventDefault(),e.stopPropagation(),r=!1,n=$(this).parent(),r===!1&&console.log("clicked");if(i===!1)return t.addClass("show"),i=!0;if(i===!0)return t.removeClass("show"),i=!1}),$(".touch-button").on("touchstart mousedown",function(e){return e.stopPropagation(),e.preventDefault(),$(this).on("touchmove mousemove",function(e){return r=!0,$(window).off("touchmove mousemove")})}).on("touchend mouseup",function(e){var n;e.preventDefault(),e.stopPropagation(),n=$(this).parent(".item-with-ul").find(">ul"),t.hasClass("lg-screen")===!0&&$(this).parent(".item-with-ul").siblings().find("ul.show").removeClass("show").hide();if(n.hasClass("show")===!0)return n.removeClass("show").slideUp(o.animationSpeed);if(n.hasClass("show")===!1)return n.addClass("show").slideDown(o.animationSpeed)}),$(".item-with-ul *").focus(function(){return $(this).parent(".item-with-ul").parent().find(".open").not(this).removeClass("open").hide(),$(this).parent(".item-with-ul").find(">ul").addClass("open").show()}),s(),$(window).on("resize",s)}}).call(this);